### ISSUE TITLE
polcal worker

### ISSUE THREAD

**Issue by paoloserra** [caracal-pipeline/caracal#1099]
>> but we've done away with polcal for now -- what are you going to do with it?

> I dunno, @SpheMakh put me up to it lol! But I like consistency, and I'd rather fix it than forget about it and have it bite me later. (Also, now that we've done away with polcal, it's high time to bring it back, but that's a separate discussion...)

So here's the separate discussion :)

**Comment by paoloserra** [comment]
The current plan is that @francescaLoi will take care of bringing the polcal worker back into the pipeline. When she does that, she will surely also take care of #1095 .

**Comment by bennahugo** [comment]
I've just checked that all the ingredients are still there to make this work. My pipeline tests end to end with the current stimela master. So you can just take my fleetingpol pipeline and reimplement it.

The way I do my work is to phase selfcal and then apply X and D jones matricies afterwards because the OMT is super stable with time (few ps stability). This works quite well in the sense that you can still use which imager you like.

Alternatively switch to imaging with DDFacet. I now apply P Jones on the fly so you no longer need to keep two columns if you apply leakage solutions prior to selfcal

**Comment by bennahugo** [comment]
I would strongly recommend implementing all of this with casa 4.7 as per our slack discussion

**Comment by paoloserra** [comment]
Many thanks @bennahugo . I'm sure that @francescaLoi will get in touch with questions once she's found her way through it all. And thanks for the important casa 4.7 reminder!

**Comment by PeterKamphuis** [comment]
@paoloserra @francescaLoi As this was my original task and my two scale calibration has finally merged I would be happy to help in re-development and testing where I can.

**Comment by paoloserra** [comment]
Thanks for the offer @PeterKamphuis . Let's let @francescaLoi coordinate this.
