### ISSUE TITLE
Why is inspect: label_cal called that?

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#1103]
Used to be ``label_out``, but seems to be ``label_cal`` now. https://github.com/caracal-pipeline/caracal/blob/master/caracal/schema/inspect_schema.yml#L17

But what does it have to do with "cal"?

**Comment by paoloserra** [comment]
Since you're asking, until recently we had only ever thought of running `inspect` to check the result of `crosscal`, so linking the plot names (that comes from `inspect: label_cal`) to `crosscal: label_cal` seemed like a good idea.

Then some clever person decided to run `inspect` *before* `crosscal`, and that beautiful construction collapsed.

Yeah, it should go back to `label_out` or, even better, `label_plot`. Something that says what it does.

**Comment by o-smirnov** [comment]
It was @SpheMakh's idea to inspect the raw data! :)

I hear secret rumours of ~perv~ users that want to run ``inspect`` on target data, too... I, for one, could not possibly imagine such a twisted scenario, but my rope-maker tells me such strange thoughts exist. Forsooth!

**Comment by o-smirnov** [comment]
Let's fix this in 1.0.1. Ought to be simple. The only thing is, do we change the schema, and do we try to stay backwards-compatible?

**Comment by paoloserra** [comment]
I'd go for `label_plot` as suggested by @molnard89 . Too bad for backward compatibility, it's still sufficiently early days in my opinion.

**Comment by o-smirnov** [comment]
Good point, early days, let's eradicate the little inconsistencies while we have the chance.

**Comment by o-smirnov** [comment]
BUt: release notes, first item on the list should be **WARNING: the following config options have changed, please adjust your files**.

**Comment by molnard89** [comment]
Okay, I'll change it to label_plot then and bundle it in with the fix to issue #1122
