### ISSUE TITLE
Inspect worker does not work on target MSs

### ISSUE THREAD

**Issue by SpheMakh** [caracal-pipeline/caracal#1122]
The inspect worker falls over (cannot find json summary file) when trying to inspect target data, this is because the field and the label get appended to the filename, and just the label.

**Comment by molnard89** [comment]
Can be fixed with adding a 'field' option just like we did for the flagging worker, but the inspect worker already has multiple 'fields' for all the different plots one can make. I don't think these can be used to figure out the input ms, since none of the are required or cross-checked between each other for consistency (e.g. one could select 'target' for amp vs phase and field 3 for amp vs channel).

So we still need a high level setting for the pipeline to figure out if the user wants to use the original ms, the splitted calibrator ms or splitted target ms's, and for the sake of consistency with other workers it should be 'field'... But it might get a bit confusing.

Like you could select field: 'target' and label_in: '', which means you'll be using the base ms (so the choice of field didn't matter in the end), but then set 'gcal' for one plot, and 'target' for another. And if you happen to do label_in: '_corr', this whole thing will break, because then you'll be looking at the splitted target ms which has no 'gcal' field. I know we can't protect the users in every scenario from breaking the pipeline, just wanted to put it out there.

**Comment by paoloserra** [comment]
I'm in favour of simplifying that and removing the `field` options from the individual plots. Again, not backward compatible, but we could claim that the entire `inspect` worker isn't backward compatible once we release 1.0.1 (as in #1103).

**Comment by molnard89** [comment]
> I'm in favour of simplifying that and removing the field options from the individual plots.

I like this. Users either set field: 'target' and get whatever plot they select for the target, or select 'calibrators', and get the same for all calibrators. Label_in determines which ms to use (original or splitted), and that's that. Much cleaner. You have to run it twice to get all the raw visibilities from the original ms before anything happens to the data, but that's probably not a significant overhead.

**Comment by paoloserra** [comment]
Yes. If you're really keen you could do as in the `flag` worker, where there is also a `calfields` allows you to work on selected  calibrators only.

**Comment by molnard89** [comment]
When we loop over dataid's inspect worker uses 'iobs' as the running index, while all other worker have 'i'. I know it's a very minor thing that probably no one cares about, but for the sake of consistency I can change it to 'i' in the inspect worker too. For the record: it's not an index in any other loops in the inspect worker, so nothing will break (hopefully).

**Comment by o-smirnov** [comment]
Rather you changed all the other workers to ``iobs``, just plain ``i`` is so undescriptive, but ok..

I agree with 'target' or 'calibrators' as useful settings, but we should also retain the currently recognized option of specifying a list of fields as well, for the perverse users.

Agree that per-plot fields can go (there is virtually *zero* overhead in doing inspect twice for different fields versus once for two fields).

(And do not that the truly perverse users can do an overriding ``--field`` setting in the shadems line...)

**Comment by molnard89** [comment]
Is it okay to trust the user to know their dataset well enough not to request separate plots for e.g. fcal and bpcal if that happens to be the same field in their observations? As far as I can tell, on the current master if someone asked for both, the pipeline would return the same figures just under different names. I can leave it as is, or try to think of a solution (which is not super trivial, i.e. there's none in my head right now).

**Comment by molnard89** [comment]
Scratch that, I had a quick break and got a simple idea how to do it. (Make a list to which we add field name being plotted, and if the next iteration finds the same field to visualize we just do a break.)

**Comment by o-smirnov** [comment]
Python has a built-in ``set`` type which makes this much easier. ``fields = set()`` will give you an empty set, then you do  ``fields.add(field)`` in your loop, then at the end ``list(fields)`` will give you a list of unique fields.
