### ISSUE TITLE
Documentation of line worker

### ISSUE THREAD

**Issue by gigjozsa** [caracal-pipeline/caracal#1240]
Add a remark that the image section in the line worker does not use the SoFiA parameters in the line worker but a hardcoded version.

**Comment by paoloserra** [comment]
That's not correct.

The `sofia` section of the line worker is about running SoFiA on the final cubes in order to produce a final detection mask, moment images, catalogues.

As written in the docs for `line: sofia`, "Run SoFiA source-finder to produce a detection mask, moment images and catalogues". 

That part makes correct use of the user's input, see https://github.com/caracal-pipeline/caracal/blob/2f446f2219b2938b16ad0a711df71e7311584919/caracal/workers/line_worker.py#L1098-L1130 .

The hard-coded bit is about making clean masks, but  in my opinion it is clear that `line: sofia` is not about cleaning.

**Comment by gigjozsa** [comment]
Sorry, to be precise: there is nothing wrong in the description, but I think it is too cryptic in this detail. The sofia used in the imaging section does not make use of the sofia parameters, because they are used on the final cube only. Instead source finding to create a clean mask uses its own, hard-coded setup. This is just a mental not to add this fact to the description.

**Comment by gigjozsa** [comment]
*note

**Comment by paoloserra** [comment]
This is OK?

"Run SoFiA source-finder on the final HI cubes to produce a detection mask, moment images and catalogues. Note that these settings are not used to make clean masks."

**Comment by gigjozsa** [comment]
Perfect!

**Comment by paoloserra** [comment]
closed by  https://github.com/caracal-pipeline/caracal/commit/6021afe0c880d7678869bbc3c515d1f3b59b3119

(surprisingly it allowed me to commit to master...!?)

**Comment by paoloserra** [comment]
Also updated on readthedocs now.

**Comment by gigjozsa** [comment]
That was really fast.
