### ISSUE TITLE
transform worker in concat mode overwrites input MS obsinfo.txt and summary.json

### ISSUE THREAD

**Issue by paoloserra** [caracal-pipeline/caracal#1270]

**Comment by paoloserra** [comment]
@o-smirnov this bug comes from https://github.com/caracal-pipeline/caracal/commit/dae4bb81bb4eb7f1aec3fface48a32ef00ea4efd#diff-f3991e74eb0964fb0d04ff58ecd6d2f067309ec40c7454b8ba2192f8b53526b7 , see L.229 and L.243 of the transform worker. I will revert that change, but let me know in case I'm missing something.

**Comment by o-smirnov** [comment]
I don't get it @paoloserra. I don't think that commit changes any logic does it -- it just moves the code around.

**Comment by paoloserra** [comment]
Look at those lines I pointed to, it changes the obsinfo.txt and summary.json file name you write to. Was that intentional?

**Comment by o-smirnov** [comment]
Ah no I see, the call to ``remove_output_products()`` is too inclusive. I hadn't realized there's a use case where the output MS name is the same as the input MS, which for concat it would be. In the latter case obsinfo and summary should not be removed (unless concantenation changes them?)

**Comment by paoloserra** [comment]
I don't really follow that, but I'm putting in a PR on this, let me know whether that's fine for you (it works for me both in concat and split mode)

**Comment by o-smirnov** [comment]
Ah nvm I see the real problem, it's indeed a wrong variable name.

While you're looking at this, maybe we should consider whether ``transform: obsinfo: summary_json`` should even be a user-controlled parameter. The rest of the pipeline relies on summary.json to be consistent with the MS, otherwise things fail in weird and unpredictable ways. So if transform is generating a new MS, shouldn't it always and unconditionally regenerate a summary? I'm all for giving the user rope, but allowing a ``false`` option here feels a little like pre-fabricating a noose as well...

**Comment by paoloserra** [comment]
I agree. But there's other places in the pipeline where files are created and "obsinfo-ed" (e.g., line worker). OK if we do it more self-consistently in a separate PR?
