### ISSUE TITLE
polcal breaks when feed_angle_rotation not specified at all in config file.

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#1539]
I think this default should be 0 not '': https://github.com/caracal-pipeline/caracal/blob/master/caracal/schema/polcal_schema.yml#L72, to be consistent with the specified data type.

@francescaLoi since you're busy with the polcal worker now, maybe just do the quick fix?

**Comment by francescaLoi** [comment]
@o-smirnov , the default so far is -90 deg. I prefer to enable that segment if the user specifies it. Is it okay with you?

**Comment by o-smirnov** [comment]
> @o-smirnov , the default so far is -90 deg. I prefer to enable that segment if the user specifies it. Is it okay with you?

By "enable segment" you mean enable feed rotation? 0 is the same as disabling, isn't it?

It's arguable whether -90 or 0 should be the default. I suppose since we're mostly for MeerKAT, -90 can be the default, but we should prominently warn the users somewhere? Or display a warning?

Either way, the schema cannot be "", as that breaks CARACal if nothing is specified in the user config.

**Comment by francescaLoi** [comment]
Yes, I mean enable the feed rotation. In the MeerKAT MS that I calibrated so far the angle was -90 deg.
That's why I would suggest to leave it empty as default. CARACal can output a warning/log info with the feed angle written in the MS.
If the user specifies a values than the rotation is applied. 
I think that this is the best option to deal with observations made with any telescope, not just MeerKAT.

**Comment by o-smirnov** [comment]
But the empty default crashes the parser, since it expects a legit float
number. I suggest a 0 default, which is equivalent to ignoring the section.

Cheers,
Oleg

--
